apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supercronic.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "supercronic.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "supercronic.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "supercronic.fullname" . }}
      annotations:
        checksum/crontab: {{ include "supercronic.crontabChecksum" . }}
        checksum/scripts: {{ include "supercronic.scriptsChecksum" . }}
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        fsGroup: 2000
      initContainers:
        - name: crontab-lint
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/supercronic", "-test", "/app/crontab/crontab"]
          volumeMounts:
            - name: crontab
              mountPath: /app/crontab
              readOnly: true
      containers:
        - name: supercronic
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-split-logs"
            - "/app/crontab/crontab"
            {{- if .Values.metrics.enabled }}
            - "-prometheus-listen-address=:{{ .Values.metrics.port }}"
            {{- end }}
          env:
            - name: TZ
              value: "{{ .Values.timezone }}"
            - name: POD_NAME
              valueFrom: { fieldRef: { fieldPath: metadata.name } }
            - name: POD_NAMESPACE
              valueFrom: { fieldRef: { fieldPath: metadata.namespace } }
          ports:
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            capabilities:
              drop:
{{ toYaml .Values.securityContext.capabilities.drop | indent 16 }}
          volumeMounts:
            - name: crontab
              mountPath: /app/crontab
              readOnly: true
            - name: scripts
              mountPath: /app/scripts
              readOnly: true
      volumes:
        - name: crontab
          configMap:
            name: {{ include "supercronic.fullname" . }}-crontab
        - name: scripts
          configMap:
            name: {{ include "supercronic.fullname" . }}-scripts
            defaultMode: 0755
